config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :posts do
    resource :likes, only: %i[create destroy]
  end
  get "home/about" => "home#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  with_options presence: true do
    validates :content, length: { maximum: 140 }
    validates :user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :username, presence: true
  validates :email, uniqueness: true
  validates :email, presence: true
  has_many :likes, dependent: :destroy

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find_by(id: params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id], liked_user_id: @post.user_id)
    @user = User.find_by(id: current_user.id)
    @user.point += 1
    @user.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def new
    @post = Post.new
    @user = User.find_by(id: current_user.id)
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to posts_path, alert: "不正なアクセスです。" if @post.user.id != current_user.id
  end

  def index
    @posts = Post.all.order("id DESC")
  end

  def create
    @post = Post.new(post_params)
    @post.start_time = DateTime.now
    @post.user_id = current_user.id
    @user = @post.user
    if @user.point.nil?
      @user.point = 0
      @post.save
      @user.save
      redirect_to post_path(@post), notice: "積み上げを記録しました。"
    elsif @user.point >= 3
      @user.point -= 3
      @post.save
      @user.save
      redirect_to post_path(@post), notice: "積み上げを記録しました。"
    elsif @user.point < 3
      redirect_to posts_path, notice: "積み上げを記録するにはあと#{3 - @user.point}回他の人をスゴイね！してください。"
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "更新に成功しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all.order("id DESC")
  end

  def show
    @user = User.find(params[:id])
    @liked = Like.where(liked_user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    redirect_to posts_path, alert: "不正なアクセスです。" if @user.id != current_user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新に成功しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<section class="section hero is-fullheight about-image">
<article class="media　about">
  <div class="media-content">

    <div class="content has-text-centered">
      <p style="margin: 30px">
        <strong class="is-size-3" style="font-family: cursive;">今日の積み上げアプリとは？</strong>
      </p>
    </div>
    <div class="content has-text-centered">
      <p>
        <strong class="is-size-5" style="font-family: cursive;">毎日のスキルアップのための努力をお互いに報告しあうSNSです。</strong>
      </p>
      <p>
        <strong class="is-size-5" style="font-family: cursive;">みんなで励ましあいながら、目標に向かって努力を積み上げていきましょう。</strong>
      </p>
    </div>
    <div class="content has-text-centered">
      <p style="margin: 30px;padding-top: 40px">
        <strong class="is-size-3" style="font-family: cursive;">今日の積み上げを記録するには？</strong>
      </p>
    </div>
    <div class="content has-text-centered">
      <p>
        <strong class="is-size-5" style="font-family: cursive;">他の人の積み上げを3回スゴイね！するとあなたの積み上げを1回記録することができます。</strong>
      </p>
      <p>
        <strong class="is-size-5" style="font-family: cursive;">投稿一覧から他の人の積み上げを選んでスゴイね！しましょう。</strong>
      </p>
    </div>
    <div class="content has-text-centered">
      <p style="margin: 30px;padding-top: 40px">
        <strong class="is-size-3" style="font-family: cursive;">他に何ができるの？</strong>
      </p>
    </div>
    <div class="content has-text-centered">
      <p>
        <strong class="is-size-5" style="font-family: cursive;">マイページではあなたがもらったスゴイね！の数が表示されます。</strong>
      </p>
      <p>
        <strong class="is-size-5" style="font-family: cursive;">また、過去の積み上げが反映されたカレンダーを確認することができます。</strong>
      </p>
      <p>
        <strong class="is-size-5" style="font-family: cursive;">せひ努力のモチベーション維持に活用してください。</strong>
      </p>
    </div>
  </div>
</article>
</section>

app/views/home/index.html.erb
<section class="section">
<article class="media">
  <div class="media-content" style="margin-bottom: 10px;">
    <div class="content has-text-centered">
      <p>
        <strong class="is-size-1" style="font-family: cursive;">今日の積み上げアプリ</strong>
      </p>
    </div>
    <div class="content has-text-centered">
      <p>
        <strong class="is-size-4" style="font-family: cursive;">塵も積もれば山となる！</strong>
      </p>
    </div>
  </div>
</article>
<br>
<div class="columns is-centered">
  <div class="column is-8">
    <figure>
      <div class="main-image"></div>
    </figure>
  </div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumiage2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header class="navbar" >

      <div class="navbar-brand">
        <div class="navbar-item">
          <a href="/" class="is-size-4 has-text-weight-semibold	">今日の積み上げアプリ</a>
        </div>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">

        <% if user_signed_in? %>
          <div class="navbar-item">
            <%= link_to "マイページ", user_path(current_user) %>
          </div>

          <div class="navbar-item">
            <%= link_to "投稿一覧", posts_path %>
          </div>

          <div class="navbar-item">
            <%= link_to "新規投稿", new_post_path %>
          </div>

          <div class="navbar-item">
            <%= link_to "ユーザー一覧", users_path %>
          </div>

          <div class="navbar-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </div>

        <% else %>

          <div class="navbar-item">            
            <%= link_to "ABOUT", home_about_path %>
          </div>

          <div class="navbar-item">
            <%= link_to "新規登録", new_user_registration_path %>
          </div>

          <div class="navbar-item">
            <a href="/users/sign_in">ログイン</a>
          </div>

        <% end %>

        </div>

      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        積み上げた内容の編集
      </h1>
    </div>
  </div>
</section>

<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %>pfohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @post do |f| %>

          <div class="field">
            <%= f.label :content, "積み上げた内容", class: "label" %>
            <%= f.text_area :content, class: "textarea" %>
          </div>

          <%= f.submit '投稿', class: "button is-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        みんなの積み上げ一覧
      </h1>
    </div>
  </div>
</section>

<div class="container">
  <div class="columns is-centered">
    <div class="column is-11">
      <% @posts.each do |post| %>
      <article class="box media">
        <figure class="media-left">
          <p class="image is-64x64">
            <% if post.user.image? %>
            <%= image_tag post.user.image.url %>
            <% else %>
            <%= image_tag "/user_images/jisin_app_user.png" %>
            <% end %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p><strong><%= link_to(post.user.username, user_path(post.user.id)) %></strong><br>
              <%= link_to(post.content, post_path(post) ) %><br>
              <small><p>
                <% if  current_user.already_liked?(post) %>
                  既にスゴイね！済です　
                <% else %>
                <%= link_to(post_likes_path(post),method: :post)do %>
                スゴイね！をする　
                <% end %>
                <% end%>
<time datetime="2016-1-1"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></time>
              </p></small>
            </p>
          </div>
        </div>
      </article>
      <% end %>
    </div>

  </div>

</div>

app/views/posts/new.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規投稿
      </h1>
    </div>
  </div>
</section>

<div >
  <% if @user.point == nil %>
  はじめての積み上げを記録してみよう！
  <% elsif @user.point < 3 %>
  積み上げを記録するにはあと<%= 3-@user.point %>回、他の積み上げをスゴイね！してください。
  <% end %>

  <% @post.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>

</div>



<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @post do |f| %>

          <div class="field">
            <%= f.label :content, "今日の積み上げ内容：", class: "label" %>
            <%= f.text_area :content, class: "textarea" %>
          </div>

          <%= f.submit '投稿', class: "button is-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        積み上げの内容詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-content">
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <td><%= simple_format @post.content %></td>
                </tr>
              </table>
              <small><a>
                <% if  current_user.already_liked?(@post) %>
                  既にスゴイね！済です
                <% else %>
                <%= link_to(post_likes_path(@post),method: :post)do %>
                スゴイね！をする
                <% end %>
                <% end%>
              </a>
              <time datetime="2016-1-1"><%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></time></small>
              <br>
              <% if @user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_post_path(@post), class: "button is-primary" %>
                <%= link_to("削除","/posts/#{@post.id}", method: :delete, class: "button is-primary", data: {confirm: "削除しますか？"}) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @user.username %>
          </p>
          <%= link_to user_path(@user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :image, "プロフィール画像：" %>
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
          </div>

          <%= f.submit "更新", class: "button is-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>


<div class="columns is-multiline">
  <% @users.each do |user| %>
  <div class="column is-2  ">
    <div class="card">
      <div class="card-content">
        <div class="card-image has-text-centered ">
            <figure class="image is-96x96 is-inline-block">
              <% if user.image? %>
                   <%= image_tag user.image.url %>
                <% else %>
                   <%= image_tag "/user_images/jisin_app_user.png" %>
                <% end %>
            </figure>

        </div>

      </div>
      <div class="card-content">
        <div class="media-content">
          <p class="title is-4"><%= link_to("#{user.username}", user_path(user)) %></p>
          <p class=" is-4 is-medium">総積み上げ数：<%= user.posts.count %></p>
        </div>
      </div>

    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <% if @user.image? %>
              <%= image_tag @user.image.url %>
              <% else %>
              <%= image_tag "/user_images/jisin_app_user.png" %>
              <% end %>
            </figure>

          </div>

          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="columns is-centered">
  <div class="column is-5">
    <h2  class="title" style="margin-top: 50px;">
      獲得したスゴイね！の総数 :
      <%= @liked.count %>
    </h2>
  </div>
</div>

<section  class="section">
<div class="columns is-centered">
  <div class="column is-6">
    <article class="panel is-link">
      <p class="panel-heading">
        今月の積み上げ記録
      </p>
      <<%= month_calendar events: @user.posts do |date, posts| %>
          <%= date.day %>
          <% posts.each do |post| %>
            <div>
              <%= link_to("積上済", post_path(post)) %>
            </div>
          <% end %>
        <% end %>
    </article>
  </div>


</div>

</section>